<template>
  <section id="home" class="slider-style-5  pb--110 align-items-center with-particles">

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="banner-inner">
            <div class="thumbnail gradient-border havatar gradient-animationz">
              <img id="border" class="gradient-border image gardnt" src="images/banner.jpg" alt="" />
              <span class="gradient-borders"></span>
            </div>
            <h1>Borhan Uddin</h1>

            <span class="cd-headline clip is-full-width">
              <div class="info">
                <i data-feather="file"></i>
                <span>
                  Founder &amp; CEO{" "}
                  <a href="http://www.srdreamlab.com">SR Dream Lab</a>
                </span>
              </div>
            </span>

            <div class="button-area">
              <!-- <BannerSocial /> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'BannerSec',
  components: {
    HomePage
  }
}
</script>

